name: Update test coverage

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - 'src/cofi/**'
      - 'pyproject.toml'
      - '!src/cofi/version.py'
  pull_request:
    types:
      - ready_for_review
    paths:
      - 'src/cofi/**'
      - 'pyproject.toml'
      - '!src/cofi/version.py'

jobs:
  code_coverage:
    if: github.repository_owner == 'inlab-geo'
    name: Run coverage on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get tags
        run: |
          git fetch --tags origin
          git describe
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r envs/requirements_test.txt
          pip install .
      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest --disable-warnings
          coverage report
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
