name: Workflow for Codecov CoFI
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/cofi/**'
      - 'pyproject.toml'
      - '!src/cofi/_version.py'
  pull_request:
    types:
      - ready_for_review
    paths:
      - 'src/cofi/**'
      - 'pyproject.toml'
      - '!src/cofi/_version.py'
jobs:
  code_coverage:
    name: Run coverage on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up environment
        run: |
          $CONDA/bin/conda update conda
          $CONDA/bin/conda info
          $CONDA/bin/conda env update --file envs/environment_test.yml --name base
          $CONDA/bin/pip install -e ".[all]"
      - name: Run tests and collect coverage
        run: |
          $CONDA/bin/coverage run -m pytest --disable-warnings
          $CONDA/bin/coverage report
          $CONDA/bin/coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2